"""Pongo codec tests — round-trips, eraser logic, and Java byte-equality."""

from __future__ import annotations

import math
import struct

import numpy as np
import pytest

from lastra.codecs import _pongo_eraser as eraser
from lastra.codecs.pongo import decode, encode


def _bits_equal(actual: np.ndarray, expected: list[float]) -> None:
    assert len(actual) == len(expected)
    for i, (a, e) in enumerate(zip(actual, expected, strict=False)):
        assert struct.pack("<d", float(a)) == struct.pack("<d", float(e)), (
            f"row {i}: {a} != {e}"
        )


def test_empty_roundtrip() -> None:
    assert encode([]) == b""
    assert decode(b"", 0).size == 0


def test_decimal_native_2dp_roundtrip() -> None:
    values = [65007.28, 65007.31, 65007.30, 65007.32, 65007.32]
    blob = encode(values)
    np.testing.assert_array_equal(decode(blob, len(values)), values)


def test_identical_values_roundtrip() -> None:
    values = [3.14, 3.14, 3.14]
    blob = encode(values)
    np.testing.assert_array_equal(decode(blob, len(values)), values)


def test_mixed_dp_and_zero_roundtrip() -> None:
    values = [-12.5, -12.6, 0.0, 100.0, 1.234]
    blob = encode(values)
    np.testing.assert_array_equal(decode(blob, len(values)), values)


def test_special_values_roundtrip() -> None:
    values = [math.nan, 1.5, math.inf]
    blob = encode(values)
    decoded = decode(blob, len(values))
    _bits_equal(decoded, values)


def test_non_representable_decimals_roundtrip() -> None:
    """0.1, 0.2, 0.3 cannot be exactly represented in binary; Pongo must
    detect that and fall through to the not-erased "10" flag path."""
    values = [0.1, 0.2, 0.3]
    blob = encode(values)
    np.testing.assert_array_equal(decode(blob, len(values)), values)


def test_count_mismatch_rejected() -> None:
    blob = encode([1.0, 2.0])
    with pytest.raises(ValueError, match="count mismatch"):
        decode(blob, 5)


# --- Eraser unit tests --------------------------------------------------

def test_detect_dp_for_clean_2dp() -> None:
    # 65007.28 is decimal-native at 2 dp.
    assert eraser.detect_decimal_places(65007.28) == 2
    assert eraser.detect_decimal_places(0.5) == 1
    assert eraser.detect_decimal_places(100.0) == 0


def test_detect_dp_returns_negative_for_special_values() -> None:
    assert eraser.detect_decimal_places(0.0) == -1
    assert eraser.detect_decimal_places(math.inf) == -1
    assert eraser.detect_decimal_places(math.nan) == -1


def test_erase_and_restore_roundtrip() -> None:
    value = 65007.28
    bits = struct.unpack("<Q", struct.pack("<d", value))[0]
    dp = eraser.detect_decimal_places(value)
    erasable = eraser.compute_erasable_bits(value, dp)
    erased = eraser.erase_bits(bits, erasable)
    restored = eraser.restore(erased, dp)
    assert restored == bits


# --- Cross-implementation: bytes generated by lastra-java PongoCodec ----

JAVA_FIXTURES = {
    "prices_2dp": (
        [65007.28, 65007.31, 65007.30, 65007.32, 65007.32],
        "0500000040efbde8f5c28f5cc5fdf8ae147af86700000018bf0b90",
    ),
    "identical": ([3.14, 3.14, 3.14], "0300000040091eb851eb851fc5d6bd70a3d70a3e00"),
    "mixed_dp": (
        [-12.5, -12.6, 0.0, 100.0, 1.234],
        "05000000c029000000000000c3c82ec0a60149d202c863c2b7faabe0",
    ),
    "special": ([math.nan, 1.5, math.inf], "030000007ff8000000000000c3841d84c801"),
    "non_repr": (
        [0.1, 0.2, 0.3],
        "030000003fb999999999999ac3a76e33333333333351a0000000000000",
    ),
}


def test_python_encode_matches_java_byte_for_byte() -> None:
    for label, (values, expected_hex) in JAVA_FIXTURES.items():
        produced = encode(values).hex()
        assert produced == expected_hex, (
            f"{label}: python produced {produced}, java produced {expected_hex}"
        )


def test_python_decode_of_java_bytes_matches_input() -> None:
    for label, (values, hex_blob) in JAVA_FIXTURES.items():
        decoded = decode(bytes.fromhex(hex_blob), len(values))
        _bits_equal(decoded, values)
