"""VARLEN family tests — round-trips + byte-equality vs lastra-java fixtures."""

from __future__ import annotations

import pytest

from lastra.codecs.varlen import (
    COMPRESSION_GZIP,
    COMPRESSION_NONE,
    COMPRESSION_ZSTD,
    decode,
    encode,
)


def test_uncompressed_roundtrip() -> None:
    values = [b"hello", b"world", b"", b"\x00\x01\x02"]
    blob = encode(values, COMPRESSION_NONE)
    assert decode(blob, len(values)) == values


def test_zstd_roundtrip() -> None:
    values = [b"price=" + str(i).encode() for i in range(1000)]
    blob = encode(values, COMPRESSION_ZSTD)
    assert decode(blob, len(values)) == values


def test_gzip_roundtrip() -> None:
    values = [b"one", b"two", None, b"four"]
    blob = encode(values, COMPRESSION_GZIP)
    assert decode(blob, len(values)) == values


def test_nulls_roundtrip_in_each_compression() -> None:
    values = [b"a", None, b"bcd", None]
    for comp in (COMPRESSION_NONE, COMPRESSION_ZSTD, COMPRESSION_GZIP):
        blob = encode(values, comp)
        assert decode(blob, len(values)) == values


def test_empty_input_returns_empty_list() -> None:
    blob = encode([], COMPRESSION_NONE)
    assert decode(blob, 0) == []


def test_decode_empty_buffer_with_zero_count() -> None:
    assert decode(b"", 0) == []


def test_unknown_compression_marker_rejected() -> None:
    with pytest.raises(ValueError, match="unknown VARLEN compression"):
        encode([b"x"], compression=99)
    with pytest.raises(ValueError, match="unknown VARLEN compression"):
        decode(bytes([99]) + b"\x00" * 8, 1)


# --- Cross-implementation: bytes generated by lastra-java VarlenCodec -------

JAVA_FIXTURES = {
    # Two UTF-8 strings, no compression
    "two_strings_none": (
        [b"hello", b"world"],
        COMPRESSION_NONE,
        "00120000000500000068656c6c6f05000000776f726c64",
    ),
    # Mix of values and NULLs (length = -1)
    "with_nulls_none": (
        [b"a", None, b"bcd", None],
        COMPRESSION_NONE,
        "00140000000100000061ffffffff03000000626364ffffffff",
    ),
    # ZSTD-compressed two strings (zstd output is deterministic for same input + level)
    "two_strings_zstd": (
        [b"hello", b"world"],
        COMPRESSION_ZSTD,
        "01120000001b00000028b52ffd20129100000500000068656c6c6f05000000776f726c64",
    ),
}


def test_python_decode_of_java_bytes() -> None:
    for label, (values, _comp, hex_blob) in JAVA_FIXTURES.items():
        decoded = decode(bytes.fromhex(hex_blob), len(values))
        assert decoded == values, f"{label}: decode mismatch"


def test_python_encode_uncompressed_matches_java_bytes() -> None:
    """No-compression payloads must be byte-for-byte identical."""
    for label, (values, comp, hex_blob) in JAVA_FIXTURES.items():
        if comp != COMPRESSION_NONE:
            continue
        produced = encode(values, comp).hex()
        assert produced == hex_blob, f"{label}: bytes differ ({produced} vs {hex_blob})"
