"""Gorilla codec tests — round-trips, edge cases, and Java byte-equality."""

from __future__ import annotations

import math

import numpy as np
import pytest

from lastra.codecs.gorilla import decode, encode


def _bits_equal(actual: np.ndarray, expected: list[float]) -> None:
    """NaN-aware bitwise equality — Gorilla preserves raw IEEE 754 bits."""
    import struct

    assert len(actual) == len(expected), f"length mismatch: {len(actual)} vs {len(expected)}"
    for i, (a, e) in enumerate(zip(actual, expected, strict=False)):
        a_bits = struct.pack("<d", float(a))
        e_bits = struct.pack("<d", float(e))
        assert a_bits == e_bits, f"row {i}: bits {a_bits.hex()} != {e_bits.hex()} ({a} vs {e})"


def test_empty_roundtrip() -> None:
    assert encode([]) == b""
    assert decode(b"", 0).size == 0


def test_simple_roundtrip() -> None:
    values = [1.0, 2.0, 3.0, 4.0, 5.0]
    blob = encode(values)
    np.testing.assert_array_equal(decode(blob, len(values)), values)


def test_prices_roundtrip() -> None:
    values = [65007.28, 65007.31, 65007.30, 65007.32, 65007.32]
    blob = encode(values)
    np.testing.assert_array_equal(decode(blob, len(values)), values)


def test_repeated_value_compresses_to_single_zero_bit_per_repeat() -> None:
    n = 100
    values = [3.14] * n
    blob = encode(values)
    # 4 bytes count + 8 bytes first + (n-1) zero bits → ceil((n-1)/8) bytes for the body.
    expected_size = 4 + 8 + ((n - 1) + 7) // 8
    assert len(blob) == expected_size
    np.testing.assert_array_equal(decode(blob, n), values)


def test_special_doubles_roundtrip() -> None:
    values = [math.nan, 1.0, math.inf, -0.0]
    blob = encode(values)
    decoded = decode(blob, len(values))
    _bits_equal(decoded, values)


def test_zero_then_small_roundtrip() -> None:
    values = [0.0, 0.0, 0.0, 1e-10, 1e-10]
    blob = encode(values)
    np.testing.assert_array_equal(decode(blob, len(values)), values)


def test_count_mismatch_rejected() -> None:
    blob = encode([1.0, 2.0])
    with pytest.raises(ValueError, match="count mismatch"):
        decode(blob, 5)


# --- Cross-implementation: bytes generated by lastra-java GorillaCodec --------

JAVA_FIXTURES = {
    "ints": ([1.0, 2.0, 3.0, 4.0, 5.0], "050000003ff0000000000000c25fffd80f585ed060"),
    "prices": (
        [65007.28, 65007.31, 65007.30, 65007.32, 65007.32],
        "0500000040efbde8f5c28f5cfefc791e479ff01c8721c8fe8ba4e93a4d00",
    ),
    "zeros_and_small": (
        [0.0, 0.0, 0.0, 1e-10, 1e-10],
        "050000000000000000000000317deedbe6fecebdedd8",
    ),
    "special": (
        [math.nan, 1.0, math.inf, -0.0],
        "040000007ff8000000000000c26400d00180cfff",
    ),
    "identical": ([3.14, 3.14, 3.14, 3.14], "0400000040091eb851eb851f00"),
}


def test_python_encode_matches_java_byte_for_byte() -> None:
    for label, (values, expected_hex) in JAVA_FIXTURES.items():
        produced = encode(values).hex()
        assert produced == expected_hex, (
            f"{label}: python produced {produced}, java produced {expected_hex}"
        )


def test_python_decode_of_java_bytes_matches_input() -> None:
    for label, (values, hex_blob) in JAVA_FIXTURES.items():
        decoded = decode(bytes.fromhex(hex_blob), len(values))
        _bits_equal(decoded, values)
