"""End-to-end :class:`LastraReader` tests against fixtures written by the
lastra-java reference (LastraWriter v0.8.0 + alp-java 0.2.1).

The ``.lastra`` blobs in ``tests/fixtures/`` were generated by a small
GenLastraFixture driver that mirrors the README snippets — code lives at
the bottom of this module's docstring so anyone can regenerate them.

Generation snippet::

    LastraWriter w = new LastraWriter(out);
    w.addSeriesColumn("ts", Lastra.DataType.LONG, Lastra.Codec.DELTA_VARINT);
    w.addSeriesColumn("opn", Lastra.DataType.DOUBLE, Lastra.Codec.ALP);
    ...
    w.writeSeries(5, ts, opn, hig, low, cls, vol);
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from lastra import Codec, DataType, LastraReader

FIXTURE_DIR = Path(__file__).parent / "fixtures"


def _load(name: str) -> bytes:
    return (FIXTURE_DIR / name).read_bytes()


# --- File 1: simple ticker (5 rows, 6 columns, no events, no row groups) ---

def test_ticker_header_and_descriptors() -> None:
    r = LastraReader.from_bytes(_load("lastra_ticker.lastra"))
    assert r.series_row_count == 5
    assert r.events_row_count == 0
    assert r.has_checksums  # writer enables it by default
    assert [c.name for c in r.series_columns] == ["ts", "opn", "hig", "low", "cls", "vol"]
    assert r.event_columns == []
    codecs = [c.codec for c in r.series_columns]
    assert codecs == [Codec.DELTA_VARINT, Codec.ALP, Codec.ALP, Codec.ALP, Codec.PONGO, Codec.GORILLA]
    types = [c.data_type for c in r.series_columns]
    assert types == [DataType.LONG, DataType.DOUBLE, DataType.DOUBLE,
                     DataType.DOUBLE, DataType.DOUBLE, DataType.DOUBLE]


def test_ticker_read_long_column() -> None:
    r = LastraReader.from_bytes(_load("lastra_ticker.lastra"))
    expected = [1700000000000, 1700000001000, 1700000002000, 1700000003000, 1700000004000]
    np.testing.assert_array_equal(r.read_series_long("ts"), expected)


def test_ticker_read_alp_column() -> None:
    r = LastraReader.from_bytes(_load("lastra_ticker.lastra"))
    expected = [65007.28, 65007.31, 65007.30, 65007.32, 65007.32]
    np.testing.assert_array_equal(r.read_series_double("opn"), expected)


def test_ticker_read_pongo_and_gorilla_columns() -> None:
    r = LastraReader.from_bytes(_load("lastra_ticker.lastra"))
    np.testing.assert_array_equal(
        r.read_series_double("cls"),
        [65007.28, 65007.31, 65007.30, 65007.32, 65007.32],
    )
    np.testing.assert_array_equal(
        r.read_series_double("vol"),
        [1.5, 2.5, 3.5, 4.5, 5.5],
    )


# --- File 2: series + events + column metadata ----------------------------

def test_with_events_decoder_handles_metadata_and_event_section() -> None:
    r = LastraReader.from_bytes(_load("lastra_with_events.lastra"))
    assert r.series_row_count == 3
    assert r.events_row_count == 2
    assert [c.name for c in r.event_columns] == ["ts", "type"]

    close_col = r.get_series_column("close")
    assert close_col.metadata == {"indicator": "close", "src": "binance"}

    np.testing.assert_array_equal(
        r.read_series_long("ts"),
        [1700000000000, 1700000001000, 1700000002000],
    )
    np.testing.assert_array_equal(
        r.read_series_double("close"),
        [100.10, 100.20, 100.30],
    )
    np.testing.assert_array_equal(
        r.read_event_long("ts"),
        [1700000000500, 1700000002500],
    )
    assert r.read_event_binary("type") == [b"buy", b"sell"]


# --- File 3: row groups ---------------------------------------------------

def test_row_groups_metadata_and_concatenated_read() -> None:
    r = LastraReader.from_bytes(_load("lastra_row_groups.lastra"))
    # 7 rows / row-group-size 3 → 3 RGs (3, 3, 1)
    assert r.row_group_count == 3
    rgs = r.row_group_stats
    assert [rg.row_count for rg in rgs] == [3, 3, 1]
    # Reading the whole column reassembles the row groups in order
    expected_ts = [1700000000000 + i * 1000 for i in range(7)]
    expected_close = [100.0 + i * 0.5 for i in range(7)]
    np.testing.assert_array_equal(r.read_series_long("ts"), expected_ts)
    np.testing.assert_array_equal(r.read_series_double("close"), expected_close)


def test_row_groups_partial_read() -> None:
    r = LastraReader.from_bytes(_load("lastra_row_groups.lastra"))
    # Reading only the third row group returns 1 row (the trailing rg).
    chunk = r.read_row_group_long(2, "ts")
    assert chunk.tolist() == [1700000006000]


def test_footer_size_hint_helper() -> None:
    blob = _load("lastra_ticker.lastra")
    size = LastraReader.read_footer_size(blob[-8:])
    assert size > 0
    # Bogus trailer returns -1
    assert LastraReader.read_footer_size(b"deadbeefdead") == -1
